POST http://127.0.0.1:5000/calculate HTTP/1.1
content-type: application/json


{
    "persons": {
        "Company A": {
            "EBITDA": { "2024": 0 },
            "revenue": { "2024": 0 },
            "corporate_tax": { "2024": null }
         }
    }
}
