POST http://127.0.0.1:5000/calculate HTTP/1.1
content-type: application/json


{
    "persons": {
        "John": {
            "is_government": { "2024": true },
            "taxable_income": { "2024": null },
            "corporate_tax": { "2024": null }
         }
    }
}